version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev:client"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: sh -c "npm install && npm run build:server && node dist/server/index.js"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dockitback
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=dockitback
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_super_secret_key
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dockitback
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 